# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0cde5f0c7cfee1df63c74984b37bf793000e8bd7f87bf6b3aaac9c7e235449dc439b3347058b82a7c8f82f26a63366579c91425d952165cca381f0c100e8c60b

test:
  secret_key_base: fc9ed92e19d92f4b87a4f5ce6babf1c3ae80e402eafcebc2f99a38a79f9b72ad975638e2e58316f08a2d675aecef66fab496249f13af2608afeeeeb635b91af6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
